# Generated by Django 2.2 on 2020-01-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Sender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
