# Generated by Django 2.2 on 2020-01-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200104_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Sender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Title',
            field=models.CharField(default='massage', max_length=100),
            preserve_default=False,
        ),
    ]
